categories:
  Food:
  - 4pk
  - almnds
  - artisan roll
  - asian family
  - avocado
  - bagel
  - bangrak market
  - baskets
  - bbq
  - beef
  - ben jerry's
  - berry
  - biscoff
  - blueberries
  - bread
  - broken yolk
  - buffet
  - burger king
  - burrito
  - buter croiss
  - cafe
  - carrot
  - cheese
  - cherries
  - cherry
  - chinese
  - chuck roast
  - coconut roll
  - coffee
  - cold stone
  - coldstone
  - costco-/
  - costco-gs
  - costco-ie org
  - costco-ks
  - costco-org
  - cottage chse
  - cream
  - dan gui
  - dim sum
  - doritos
  - dough zone
  - duckhorn cab
  - durianicecrm
  - eggs
  - fantuan
  - ferrero
  - flour
  - food
  - fred meyer
  - grain house
  - grapes
  - half&half
  - heytea
  - hmart
  - hot dog
  - housemart highlands
  - hungrypanda
  - hvst snaps
  - ihop
  - in-n-out
  - italian
  - joey bellevue
  - kitchen
  - kiwi
  - lamb
  - laughing cow
  - lindt gold
  - little frenchie
  - buffet
  - mart bellevue
  - matcha
  - mcdonald
  - nanas green
  - north (bellevue)
  - nuggets
  - oats
  - pantene1
  - parchment
  - peach
  - pepper
  - pistachio
  - pizza
  - pork
  - potatochips
  - pummelo
  - qfc
  - queso chihua
  - ranch house
  - recalled
  - restaurant
  - reynolds
  - rice
  - romaine
  - saffron grill
  - safeway
  - salad
  - salt
  - sandwich
  - scrubmmy
  - seafood
  - sesame
  - shake shack
  - shrimp
  - slice pep
  - soda
  - squish
  - starbucks
  - store newcastle
  - straw bana
  - strawberries
  - subway
  - sugar
  - sushi
  - t&t
  - taco
  - taste of xi'an
  - taste xi'an
  - ten seconds
  - tenseconds
  - tgtg
  - thai
  - than brothers
  - tian
  - tilapia flts
  - tomato
  - trader joe
  - trout
  - turkey
  - vanilla cup
  - vinegar
  - wagyu grind
  - walmart
  - watermelon
  - whole foods
  - wok
  - yogurt
  Travel:
  - airport
  - ampm
  - arco
  - carlsbad
  - chevron
  - delta air
  - flight
  - gas
  - hotel
  - lego
  - lyft
  - olympic national
  - priceln
  - shell
  - sixt
  - spokane
  - uber
  Shopping:
  - amazon
  - aritzia
  - barnes noble
  - beenverified
  - best buy
  - claire
  - costco-***bounty***
  - costco-**klnx ultr*
  - costco-45qtstor
  - costco-bath mat
  - costco-cetaphil crm
  - costco-col. blanket
  - costco-comfort mat
  - costco-cuis toaster
  - costco-dyson v15
  - costco-far niente
  - costco-foldingwagon
  - costco-hotoscrubber
  - costco-khombu mens
  - costco-klxtrustcare
  - costco-ks diced
  - costco-ks dish
  - costco-ks microfibr
  - costco-mc1.8qtk
  - costco-mortarpestle
  - costco-ninja creami
  - costco-pokemon
  - costco-rice cooker
  - costco-scrub bubbl
  - costco-senso adv
  - costco-shine muscat
  - costco-soap
  - costco-stahee
  - costco-substanchard
  - costco-swiffer wet
  - costco-tidepods
  - costco-womens
  - goodwill
  - grasons
  - groupon
  - home depot
  - homegoods
  - ikea
  - jewelry
  - kennellyamericanmus
  - kiehl
  - north bend
  - nyx*amerikiosk corp.
  - outlet
  - rei
  - rose
  - skillets
  - sport
  - swain's general
  - target
  - the ups
  - under armour
  - university district
  Utilities:
  - at&t
  - avanewcastcommo
  - charging
  - charmin
  - city bellevue
  - city of bellevue
  - costco-arm&hammer
  - goodtogo
  - ici*fee bellevue
  - parking
  - paybyphone
  - progressive
  - puget
  - puget sound energy
  - tesla
  - too good
  Healthcare:
  - all care
  - clinic
  - coq
  - cvs
  - eye
  - ks calc+d3
  - medical
  - nb 1400mg
  - overlake
  - pantene
  - pearle vision
  - pharm
  - proliance
  - pronamel
  - walgreens
  Entertainment:
  - amc
  - boomers
  - bouldering
  - camp
  - climbing
  - edgeworks
  - escape
  - farms
  - legoland
  - netflix
  - our family
  - spotify
  - summit
  - vending
  Services:
  - basis independent
  - codecademy
  - dol
  - itin
  - king county
  - lkg
  - membership
  - openai
  - robinson ctr
  - salon
  - secretary
  - service fee
  - tax
  - tt fed
  - u-haul
  - us treas
  - uscis
  - usps
  Payment:
  - autopay
  - online payment
  - pay
  - payment
  - thank you
